[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$aHbcZBHW$EhKTAWBj/4tm5Nggci/ay."
  ]

[http.routers.api]
  rule = "Host(`traefik.doruce.website`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
